### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by bakalarczuk** [Neelarghya/tesseract-unity#1]
Hi. Thank you for your great work.
I want to ask is it possible to make it multilanguage without switching?

**Comment by Neelarghya** [comment]
Yes, add your language specific TessData

**Comment by bakalarczuk** [comment]
Yes. I did and working like a charm.
I mean rather something like: I have two textures, one in Polish, second i English, and reader can read both in runtime without some kind of button switch between them. Now I can read only English or Polish. Is it possible to make it multilanguage on init?

**Comment by Neelarghya** [comment]
Nope... You need a language detection algo/api to preprocess...
