### ISSUE TITLE
Tesseract version: System.DllNotFoundException - tesseract

### ISSUE THREAD

**Issue by Calvin2274** [Neelarghya/tesseract-unity#2]
Unity 2018.4.24f1
------------------
Plugins: Couldn't open Assets/Plugins/Mac/tesseract.bundle, error: dlopen(Assets/Plugins/Mac/tesseract.bundle, 2): Library not loaded: /usr/local/opt/leptonica/lib/liblept.5.dylib
  Referenced from: /Users/mingwaichan/Documents/Unity Projects/tesseract-unity-master/Assets/Plugins/Mac/tesseract.bundle
  Reason: image not found
TesseractDriver:CheckTessVersion() (at Assets/Scripts/TesseractDriver.cs:19)
TesseractDemoScript:Recoginze(Texture2D) (at Assets/Scripts/TesseractDemoScript.cs:27)
TesseractDemoScript:Start() (at Assets/Scripts/TesseractDemoScript.cs:20)

---------------

Plugins: Couldn't open Assets/Plugins/Mac/tesseract.bundle, error: dlopen(Assets/Plugins/Mac/tesseract.bundle, 2): Library not loaded: /usr/local/opt/leptonica/lib/liblept.5.dylib
  Referenced from: /Users/mingwaichan/Documents/Unity Projects/tesseract-unity-master/Assets/Plugins/Mac/tesseract.bundle
  Reason: image not found
TesseractWrapper:Version() (at Assets/Scripts/TesseractWrapper.cs:72)
TesseractDriver:CheckTessVersion() (at Assets/Scripts/TesseractDriver.cs:19)
TesseractDemoScript:Recoginze(Texture2D) (at Assets/Scripts/TesseractDemoScript.cs:27)
TesseractDemoScript:Start() (at Assets/Scripts/TesseractDemoScript.cs:20)

----------------------

Tesseract version: System.DllNotFoundException - tesseract
UnityEngine.Debug:LogError(Object)
TesseractDriver:CheckTessVersion() (at Assets/Scripts/TesseractDriver.cs:26)
TesseractDemoScript:Recoginze(Texture2D) (at Assets/Scripts/TesseractDemoScript.cs:27)
TesseractDemoScript:Start() (at Assets/Scripts/TesseractDemoScript.cs:20)

**Comment by Neelarghya** [comment]
I suspect your mac is missing the leponica library as mentioned by "Library not loaded: /usr/local/opt/leptonica/lib/liblept.5.dylib"
System.DllNotFoundException is shown even if the dll is found but a dependency isn't present, so it's not Assets/Plugins/Mac/tesseract.bundle which has the issue
Things you can try... 
1. Install Tesseract locally -- brew install tesseract
2. If that itself doesn't get all the dependencies thus fixing the issue, manually move the /usr/local/opt/leptonica/lib/liblept.5.dylib that got installed and place it in your /Assets/Plugins/Mac/ , change it's extension from .dylib to .bundle

**Comment by Calvin2274** [comment]
Thank you very much ! works after "brew install tesseract" in terminal. Wonder do i need to install again when build as Standalone for Windows ?

**Comment by Neelarghya** [comment]
Happy to help, I never really got the chance to test on all platforms, Windows x64 should work fine, but let me know
