### ISSUE TITLE
I have an error.

### ISSUE THREAD

**Issue by ViousGod** [Neelarghya/tesseract-unity#3]
First, thank you for sharing this project!
When I import to my unity, it show "TesseractWrapper.cs(195,58): error CS0103: The name 'str_ptr' does not exist in the current context"
Could you solve this problem?

**Comment by ViousGod** [comment]
I solve the problem!
I just change str_ptr to stringPtr, then it works!

**Comment by Neelarghya** [comment]
Thank you for bringing this up, have updated the repo with the changes. Commit: [867cff4](https://github.com/Neelarghya/tesseract-unity/commit/867cff44b458770eae131678525cb7651ebe9caa)
