### ISSUE TITLE
System.DllNotFoundException in android

### ISSUE THREAD

**Issue by shalumhmd** [Neelarghya/tesseract-unity#7]
When I build apk file it shows an error

System.DllNotFoundException - Unable to load DLL 'libtesseract.so': The specified module could not be found.

![Screenshot_20210119-125459](https://user-images.githubusercontent.com/67310272/105001355-a3b1f180-5a55-11eb-8286-0cf598b4a8c6.png)

Anyone solved this issue

**Comment by Neelarghya** [comment]
Could you unzip (change extension to .zip or .rar and unzip/unrar) the APK that you are building and check if all the .so files that are there inside the Assets/Plugins/Android are also packaged in your APK?

**Comment by shalumhmd** [comment]
hi Neelarghya,
The build works fine when I build your git project.

But when I export the files to another project and build them in android, it shows the above error.

I check the plugin folder and apk. it contains all the so files

**Comment by re-cheid** [comment]
Had the same problem.
Seems like in the build settings the scripting backend must be Mono.
This problem always occpurs when IL2CCP is selected
