### ISSUE TITLE
The name 'str_ptr' does not exist in the current context (for UNITY_EDITOR || UNITY_STANDALONE_WIN)

### ISSUE THREAD

**Issue by dmax1** [Neelarghya/tesseract-unity#8]
When a package is imported, the error shows:
Assets\Scripts\TesseractWrapper.cs(195,58): error CS0103: The name 'str_ptr' does not exist in the current context

When "str_ptr" attribute is replaced with "stringPtr" in TesseractWrapper.cs it can compile and run in the editor when is selected "PC, Mac & Linux Standalone" platform.

`#if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN

      string recognizedText = Marshal.PtrToStringAnsi (str_ptr);
#else  

      string recognizedText = Marshal.PtrToStringAuto(stringPtr);
#endif`

**Comment by shalumhmd** [comment]
change str_ptr to stringPtr

**Comment by Neelarghya** [comment]
Already fixed in https://github.com/Neelarghya/tesseract-unity/commit/867cff44b458770eae131678525cb7651ebe9caa closing issue
